language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

# Run tests
script: phpunit --configuration tests/phpunit.xml --coverage-clover=coverage.clover --coverage-text tests

after_script:
  # Send coverage stats
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
